[package]
name = "dlm"
version = "0.3.5"
authors = ["Arnaud Gourlay <arnaud.gourlay@gmail.com>"]
description = "Minimal download manager"
edition = "2021"

[dependencies]
futures = "0.3.30"
futures-util = "0.3.30"
reqwest = { version = "0.11.24", default-features = false, features = ["gzip", "rustls-tls"] }
tokio-stream = { version = "0.1.14", features = ["io-util"] }
tokio = { version = "1.35.1", features = ["rt-multi-thread", "fs", "macros"] }
tokio-retry = "0.3.0"
async-channel = "2.1.1"
chrono = "0.4.33"
clap = { version = "4.4.18", features = ["cargo"] }
indicatif = "0.17.7"
thiserror = "1.0.56"
rand = "0.8.5"
